### ISSUE TITLE
Namespace not in accepted input list?

### ISSUE THREAD

**Issue by milanvanschaik** [hiberbee/github-action-skaffold#12]
I'm trying to implement Skaffold in GH actions trough this wonderful action, but it seems like I can't set the namespace as an input.

**Current behaviour**
For example, with the following setup:
```
    - uses: hiberbee/github-action-skaffold@1.6.0
      with:
        command: run
        profile: staging
        namespace: staging
```
I retrieve the following error:
```
Unexpected input(s) 'namespace', valid inputs are ['skaffold-version', 'container-structure-test-version', 'command', 'build-image', 'cache-artifacts', 'default-repo', 'filename', 'kubeconfig', 'kube-context', 'working-dir', 'profile', 'skip-tests', 'tag']
```

**Expected behaviour**
namespace should be a valid argument as in the documentation. It's also implemented in the code.

I'm wondering if there's a reason why it isn't listed as valid input?
