### ISSUE TITLE
Stop passing default args for unsupported args

### ISSUE THREAD

**Issue by alaasdk** [hiberbee/github-action-skaffold#18]
All default values for all args got passed to the `Skaffold` command, thus some of the commands fails with some of these arguments.. 

ex. 
`diagnose` or `deploy` fails when receives `--cache-file` argument and exit with `code 127` with error "`unknown flag: --cache-file`"

```bash
root@docker-desktop:/Users/myuser/myrepo# ./bin/skaffold deploy --cache-file=/Users/myuser/myrepo/.skaffold/cache --filename=skaffold.yaml --verbosity=warning
unknown flag: --cache-file
See 'skaffold deploy --help' for usage.
```

A solution would be extracting all available args from --help and match it with passed+default values, something like...
```typescript
const command_help = await exec(Binaries.SKAFFOLD, command, '--help')
const argsRegex = /(--\S+|-[a-zA-Z]),?\s?(\S+)?: (.+)/gm;
```

**Comment by wonderstim** [comment]
I am also running into this issue with or without the `cache: false` configured.
```
      - name: Run Skaffold Production Rendering
        uses: hiberbee/github-action-skaffold@1.26.0
        with:
          command: render
          profile: production
```
