### ISSUE TITLE
Error while installing Skaffold

### ISSUE THREAD

**Issue by dormammun** [hiberbee/github-action-skaffold#24]
```
name: Verifier e2e Test

on:
  pull_request:
    paths:
      - 'application/services/**'

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        env:
          WEB_URL: http://aloco.local
          API_URL: http://aloco.local/api
      - uses: medyagh/setup-minikube@master
      - uses: azure/setup-helm@v3
      - uses: hiberbee/github-action-skaffold@1.20.0 <<<<<<<<<
      - run: cd infrastructure/k8s && sh cmd.sh run-local
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: sudo echo "127.0.0.1 aloco.local" | sudo tee -a /etc/hosts
      - run: pnpm -F @looport/verifier install
      - run: pnpm -F @looport/verifier test
 ```

Error:
```
Run hiberbee/github-action-skaffold@1.20.0
/home/runner/work/_actions/hiberbee/github-action-skaffold/1.20.0/src/index.js:5513
      ""return __awaiter(this, void 0, void 0, function* () {
        ^^^^^^

SyntaxError: Unexpected token 'return'
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1126:15)
    at Module._compile (node:internal/modules/cjs/loader:1162:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47
```
