### ISSUE TITLE
action does not support env

### ISSUE THREAD

**Issue by Loki-Afro** [hiberbee/github-action-skaffold#25]
hey there, i noticed the action does not support env, which makes this workaround impossible, with `SKAFFOLD_LABEL` one can disable that skaffhold restarts all deployments each time
```
      - name: Run Skaffold
        uses: hiberbee/github-action-skaffold@1.27.0
        with:
          skaffold-version: '2.16.1'
          command: run
          kubeconfig: /home/runner/.kube/config
        env:
          SKAFFOLD_LABEL: skaffold.dev/run-id=ci
```
