### ISSUE TITLE
Error retrieving insecure registries

### ISSUE THREAD

**Issue by Ansen04** [hiberbee/github-action-skaffold#8]
hello, I got an error when build image to a private repository
the outputs on github action is

`error retrieving insecure registries from global config: push/pull issues may exist...`

my github action is

```
- name: Run Skaffold build
        uses: hiberbee/github-action-skaffold@latest
        with:
          command: build
          default-repo: my.private.repository
          tag: 202103091200
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: True
```

there is no error on `hiberbee/github-action-skaffold@1.4.0`
