### ISSUE TITLE
unknown flag: --cache-file

### ISSUE THREAD

**Issue by javier-b-perez** [hiberbee/github-action-skaffold#9]
I'm using the example provided in the docs (tested for 1.6 and 1.7 release)
```yaml
      - name: Setup Skaffold
        uses: hiberbee/github-action-skaffold@1.7.0
        with:
          command: diagnose

      - name: Build Docker images
        run: skaffold build
        env:
          SKAFFOLD_DEFAULT_REPO: ${{ secrets.DOCKER_REGISTRY }}
```

I get:
```shell
Run hiberbee/github-action-skaffold@1.7.0
  with:
    cache-artifacts: false
    command: diagnose
    skaffold-version: 1.32.0
    container-structure-test-version: 1.10.0
    filename: skaffold.yaml
    skip-tests: true
/usr/bin/chmod +x /home/runner/work/repo/repo/bin/skaffold
/home/runner/work/repo/repo/bin/skaffold diagnose --cache-file=/home/runner/work/repo/repo/.skaffold/cache --cache-artifacts=false --filename=skaffold.yaml --skip-tests=true
unknown flag: --cache-file
See 'skaffold diagnose --help' for usage.
Error: The process '/home/runner/work/repo/repo/bin/skaffold' failed with exit code 127
```
